### PR TITLE
LogParser can accept directories, now

### PR DESCRIPTION
**Pull request by spikegrobstein**
If it encounters a directory in the argument list, it will recursively
go through the files in it and parse them. (no tests for this use-case)

I couldn't figure out how to test this in such a way that fits in with the rest of your test suite, but some quick tests looked like it worked.

I had to process through tens of thousands of S3 logs and didn't have the time or processing power to combine them. This change saved me HOURS.

### CODE REVIEW

**Comment by barttenbrinke** [comment]
Hey Spike,
thats very nice addition! Thank you for contributing.
But as you said, it does need a test.
You could test it quite simply by adding a subdirectory to the fixtures directory named something like "log_directory" that contains two or three s3 sample files containing two or three lines each.
The test itself can be added to the integration/command_line_usage_spec, something like:

output = run("#{log_directory_fixture} --format s3")
output.any? { |line| /^Parsed requests:\s*12\s/ =~ line }.should be_true

You can add the log_directory_fixture function in helpers.rb and have it point to the created directory.

Greetings, Bart

**Comment by spikegrobstein** [comment]
Cool. Working on it. Thanks for the pointers. This is a lot easier than what I was trying to get working before.

I actually came across a couple of issues with my implementation while writing the tests so I'm working on fixing those and will update the pull request when I get that working.

**Comment by spikegrobstein** [comment]
This last commit should tie up all the loose ends.

Let me know if there's anything else I should do. Thanks!

**Comment by barttenbrinke** [comment]
Hi Spike,

very nice work! Thanks for your contribution!

Greetings, Bart

**Pull request merged**
