### PR TITLE
Display Filename in header of output Closes #122

### LINKED ISSUE #122: Inclusion of Log File's path in output
So earlier I raised an issue with inclusion of server name or some identifier in the email. That kinda sorta didnt work because the backticks got escaped by whenever gem. I'd have to schedule logging outside of my rails app which is slightly ugh.

Anyway, It would be really nice if the full path of log file being analyzed was listed in the out (html)

Hard? Want pull request?

### PR DESCRIPTION
**Pull request by asanghi**
Displays list of input files processed in header of output

### CODE REVIEW

**Comment by barttenbrinke** [comment]
This looks fine. Lets see what Travis CI says about it.

**Comment by wvanbergen** [comment]
Travis CI wasn't running due to an error in the travis config file. Can you merge (or rebase on) the latest commit from master and push to your branch? That should trigger a CI run.

**Comment by barttenbrinke** [comment]
Thank you!

**Comment by wvanbergen** [comment]
Included in the latest version: 1.12.5

**Pull request merged**
