### PR TITLE
s3 format parser more permissive, it rejected real log files

### PR DESCRIPTION
**Pull request by mindreframer**

### CODE REVIEW

**Comment by wvanbergen** [comment]
The specs appear to be failing due to a syntax error. Can you look into it?

**Comment by wvanbergen** [comment]
Seems like you're using Ruby 1.9 syntax, while we still maintain 1.8 compatibility. Should be easy to fix.

**Comment by barttenbrinke** [comment]
Yeah, especially because a lot of server environments have a system ruby which is 1.8.6 (debian, ubuntu, osx server)

**Comment by mindreframer** [comment]
:) yeah. easy fix. thx for merging!

**Pull request merged**
