### PR TITLE
Oink instance type counter

### PR DESCRIPTION
**Pull request by technicalpickles**
In addition to memory usage, Oink can log ActiveRecord instances created. Thought it would be rad to be able to parse this as well.

I have some crazy ideas for using request-log-analyzer to generate reports of leaky actions/requests, and this was just one step along the way :)

### CODE REVIEW

**Comment by wvanbergen** [comment]
Awesome work! Can't wait to see what more you have in store for this file format.

I'd like to merge it, but there's an issue with the current patch: the class names of the instantiated objects are downcased in the code, but the test still uses the string as it is found in the file. This will make the spec fail. Should be an easy fix.

```
1) RequestLogAnalyzer::FileFormat::Oink#parse_line should parse a :instance_type_counter correctly
   Failure/Error: @oink.should parse_line(line).as(:instance_type_counter).and_capture(:pid => 26364, :instance_counts =>  {'Total' => 732, 'User' => 376, 'Post' => 323, 'Comment' => 32, 'Blog' => 1})
   Expected line "Dec 13 12:00:44 storenvy rails[26364]: Instantiation Breakdown: Total: 732 | User: 376 | Post: 323 | Comment: 32 | Blog: 1"
       to capture :instance_counts as {"Total"=>732, "User"=>376, "Post"=>323, "Comment"=>32, "Blog"=>1} but was {"total"=>732, "user"=>376, "post"=>323, "comment"=>32, "blog"=>1}.
   # ./spec/unit/file_format/oink_format_spec.rb:38:in `block (3 levels) in <top (required)>'
```

**Comment by technicalpickles** [comment]
Heh, how embarrassing. I eventually decided to leave the strings as is to avoid mucking with camelcase to snakecase. Should be good now.

**Comment by wvanbergen** [comment]
Well, to be sure that your changes REALLY made it into the repository, your commits have been merged twice: both Bart and me pulled them in :)

I am very interested in what will follow!

**Comment by technicalpickles** [comment]
Any chance of getting a patch release with this in the near future? Pleeeeease? :)

I had two ideas. First, the Rails plugin for Scout uses request-log-analyzer, and reports memory stuff if oink is around. It didn't report instance counts though, since request-log-analyzer didn't report it :)

Second, which is related, is just a small tool to parse logs and spit out a concise list of memory/instance intensive actions so you can know where to start looking. I found the default oink report formats either too verbose or not verbose enough, so I was looking for a happy median.

**Comment by wvanbergen** [comment]
Sure. I released version 1.9.9. Please keep me up-to-date with your findings.

**Comment by technicalpickles** [comment]
Awesome, much appreciated!

**Pull request merged**
